import { CheckIcon, Cross2Icon, GitHubLogoIcon, MoonIcon, SunIcon } from '@radix-ui/react-icons';
import {
  BarChart,
  ChevronDownSquareIcon,
  ChevronLeft,
  ChevronLeftSquareIcon,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ImageIcon,
  Info,
  Laptop,
  LineChart,
  LogOut,
  RefreshCcwIcon,
  Settings,
  Trophy,
  User2,
  FileCheck2,
  ThumbsUp,
  ThumbsDown,
  Loader2,
  SquareDashedBottomCode,
  Car,
  Eye,
  PlusCircle,
  Trash,
  MoreVertical,
  LucideProps,
  Keyboard,
  Crown,
  Bell,
  BellDot,
  CircleDashed,
  CircleDot,
  XSquare,
} from 'lucide-react';

export const Icons = {
  sun: SunIcon,
  moon: MoonIcon,
  github: GitHubLogoIcon,
  laptop: Laptop,
  logout: LogOut,
  settings: Settings,
  chart: BarChart,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  profile: User2,
  lineChart: LineChart,
  mobileNavOpen: ChevronDownSquareIcon,
  mobileNavClosed: ChevronLeftSquareIcon,
  trophy: Trophy,
  refresh: RefreshCcwIcon,
  picture: ImageIcon,
  info: Info,
  review: FileCheck2,
  thumbsUp: ThumbsUp,
  thumbsDown: ThumbsDown,
  spinner: Loader2,
  cross: Cross2Icon,
  check: CheckIcon,
  snippet: SquareDashedBottomCode,
  race: Car,
  eye: Eye,
  addCircle: PlusCircle,
  trash: Trash,
  ellipsis: MoreVertical,
  normalBellNotification: Bell,
  unreadBellNotification: BellDot,
  unreadNotification: CircleDashed,
  readNotification: CircleDot,
  xSquare: XSquare,
  keyboard: Keyboard,
  crown: Crown,
};
